import Config

# Configure your database
config :realtime, Realtime.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "db-content-cluster",
  database: "postgres",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Configure application environment variables for development
config :realtime,
  mode: "development",
  host: "localhost:4000",
  admin_db_host: "db-admin-cluster",
  admin_db_port: "5432",
  admin_db_user: "postgres",
  admin_db_password: "postgres",
  admin_db_database: "dabblebase_admin",
  content_db_host: "db-content-cluster",
  content_db_port: "5432",
  content_db_user: "postgres",
  content_db_password: "postgres",
  auth_master_secret: "dev_secret_key_please_change_in_production"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :realtime, RealtimeWeb.Endpoint,
  # Bind to 0.0.0.0 to expose the server to the docker host machine.
  # This makes make the service accessible from any network interface.
  # Change to `ip: {127, 0, 0, 1}` to allow access only from the server machine.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "uTypJxFa/HMjQbEBzdE2/4ZXycx1eL5l1l2Hq/2YyIqDWJuJPNuRu3Ok5um+LBN0",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :realtime, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
