/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task/{task_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task Status */
        get: operations["get_task_status_api_task__task_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logs out the user by clearing the auth token cookie.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/{project_id}/auth/unc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Unc
         * @description This endpoint initiates authentication to the UNC SSO proxy for a project. The proxy will
         *     respond with an authorization token and call the `/unc/callback` endpoint for Tinkerbase
         *     to continue the UNC SSO authentication flow.
         */
        get: operations["auth_unc_api_project__project_id__auth_unc_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/{project_id}/auth/unc/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Unc Callback
         * @description This endpoint is called by the UNC SSO proxy after the user has authenticated with UNC SSO.
         *     Tinkerbase will verify the token and issue a JWT token for the user to be authenticated.
         */
        get: operations["auth_unc_callback_api_project__project_id__auth_unc_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_course_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/dropdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dropdown */
        get: operations["get_dropdown_api_course_dropdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{course_id}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Assignments
         * @description Get assignments for a specific course.
         */
        get: operations["get_assignments_api_course__course_id__assignments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{course_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Course Role
         * @description Get the role of the user in the specified course.
         */
        get: operations["get_course_role_api_course__course_id__role_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{course_id}/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Students
         * @description Get the list of students in a specific course.
         */
        get: operations["get_students_api_course__course_id__students_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_api_profile_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/dropdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dropdown */
        get: operations["get_dropdown_api_assignment_dropdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/{assignment_id}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get View */
        get: operations["get_view_api_assignment__assignment_id__view_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/{assignment_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_api_assignment__assignment_id__draft_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/{assignment_id}/configuration-sql": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Configuration Sql
         * @description Get the configuration SQL for an assignment.
         */
        get: operations["get_configuration_sql_api_assignment__assignment_id__configuration_sql_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/{assignment_id}/staff-view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Staff View
         * @description Get the staff view of an assignment.
         */
        get: operations["get_staff_view_api_assignment__assignment_id__staff_view_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/{assignment_id}/student-projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Student Projects
         * @description Get the student projects for an assignment.
         */
        get: operations["get_student_projects_api_assignment__assignment_id__student_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/{assignment_id}/group-projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Group Projects
         * @description Get the student projects for an assignment.
         */
        get: operations["get_group_projects_api_assignment__assignment_id__group_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Draft */
        post: operations["create_draft_api_assignment_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/{assignment_id}/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Rename
         * @description Rename an existing assignment.
         */
        put: operations["rename_api_assignment__assignment_id__rename_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/{assignment_id}/configuration-sql/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Test Configuration Sql
         * @description Test the configuration SQL for an assignment.
         */
        put: operations["test_configuration_sql_api_assignment__assignment_id__configuration_sql_test_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/{assignment_id}/configuration-sql/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save Configuration Sql
         * @description Save the configuration SQL for an assignment.
         */
        put: operations["save_configuration_sql_api_assignment__assignment_id__configuration_sql_save_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/{assignment_id}/configuration-sql/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Remove Configuration Sql
         * @description Reset the configuration SQL for an assignment.
         */
        put: operations["remove_configuration_sql_api_assignment__assignment_id__configuration_sql_remove_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/{assignment_id}/configuration-sql/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Reset Configuration Sql
         * @description Reset the configuration SQL for an assignment.
         */
        put: operations["reset_configuration_sql_api_assignment__assignment_id__configuration_sql_reset_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/{assignment_id}/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Groups
         * @description Get the groups of an assignment.
         */
        get: operations["get_groups_api_assignment__assignment_id__groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/{assignment_id}/group/{group_id}/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Rename Group
         * @description Rename a group in an assignment.
         */
        put: operations["rename_group_api_assignment__assignment_id__group__group_id__rename_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/{assignment_id}/group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Group
         * @description Create a new group in an assignment.
         */
        post: operations["create_group_api_assignment__assignment_id__group_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/{assignment_id}/group/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Group
         * @description Delete a group in an assignment.
         */
        delete: operations["delete_group_api_assignment__assignment_id__group__group_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/{assignment_id}/group/{group_id}/member": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Group Member
         * @description Add a member to a group in an assignment.
         */
        post: operations["add_group_member_api_assignment__assignment_id__group__group_id__member_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/{assignment_id}/group/{group_id}/member/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Group Member
         * @description Remove a member from a group in an assignment.
         */
        delete: operations["remove_group_member_api_assignment__assignment_id__group__group_id__member__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/{assignment_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Publish Assignment
         * @description Publish an assignment.
         *
         *     Note: This kicks off an asynchronous task using Celery and returns
         *     the task ID. The client can poll the task status endpoint to ensure
         *     the task has completed.
         */
        put: operations["publish_assignment_api_assignment__assignment_id__publish_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/{assignment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Assignment
         * @description Delete an assignment.
         */
        delete: operations["delete_assignment_api_assignment__assignment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AddGroupMemberRequest
         * @description Model that represents a request to add a member to a group for an assignment.
         */
        AddGroupMemberRequest: {
            /** Group Id */
            group_id: number;
            /** User Id */
            user_id: number;
        };
        /**
         * AssignmentState
         * @description Enum identifying the various states an assignment can be in.
         * @enum {string}
         */
        AssignmentState: "draft" | "unpublished" | "published";
        /**
         * CourseMembershipRole
         * @description Enum identifying the level of permissions for a course member.
         * @enum {string}
         */
        CourseMembershipRole: "owner" | "admin" | "staff" | "student";
        /**
         * CreateDraftRequest
         * @description Model that represents a request to create a draft.
         */
        CreateDraftRequest: {
            /** Name */
            name: string;
            /** Course Id */
            course_id: number;
            /** Is Group */
            is_group: boolean;
        };
        /**
         * CreateDraftResponse
         * @description Model that represents a response to creating a draft.
         */
        CreateDraftResponse: {
            /** Assignment Id */
            assignment_id: number;
        };
        /**
         * CreateGroupRequest
         * @description Model that represents a request to create a group for an assignment.
         */
        CreateGroupRequest: {
            /** Group Name */
            group_name: string;
        };
        /**
         * CreateGroupResponse
         * @description Model that represents a response to creating a group for an assignment.
         */
        CreateGroupResponse: {
            /** Group Id */
            group_id: number;
            /** Group Name */
            group_name: string;
        };
        /**
         * GetAssignmentsResponse
         * @description Model that represents a response for the assignments endpoint.
         */
        GetAssignmentsResponse: {
            /** Is Staff */
            is_staff: boolean;
            /** Assignments */
            assignments: components["schemas"]["GetAssignmentsResponse_Assignment"][];
        };
        /**
         * GetAssignmentsResponse_Assignment
         * @description Model that represents an assignment in the assignments response.
         */
        GetAssignmentsResponse_Assignment: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Is Group */
            is_group: boolean;
            state: components["schemas"]["AssignmentState"];
        };
        /**
         * GetConfigurationSQLResponse
         * @description Model that represents a response for getting the configuration SQL of an assignment.
         */
        GetConfigurationSQLResponse: {
            /** Sql */
            sql?: string | null;
            /** Sql Draft */
            sql_draft?: string | null;
            /** Sql Draft Success */
            sql_draft_success?: boolean | null;
            /** Sql Draft Error */
            sql_draft_error?: string | null;
            /** Db Url */
            db_url?: string | null;
        };
        /**
         * GetDashboardResponse
         * @description Model that represents a response for the dashboard endpoint.
         */
        GetDashboardResponse: {
            /** Most Recent Staff Course Term */
            most_recent_staff_course_term: string | null;
            /** Most Recent Student Course Term */
            most_recent_student_course_term: string | null;
            /** Other Staff Course Terms */
            other_staff_course_terms: string[];
            /** Other Student Course Terms */
            other_student_course_terms: string[];
            /** Staff Courses */
            staff_courses: {
                [key: string]: components["schemas"]["GetDashboardResponse_Course"][];
            };
            /** Student Courses */
            student_courses: {
                [key: string]: components["schemas"]["GetDashboardResponse_Course"][];
            };
        };
        /**
         * GetDashboardResponse_Course
         * @description Model that represents a course in the dashboard response.
         */
        GetDashboardResponse_Course: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Num Students */
            num_students?: number | null;
            /** Num Assignments */
            num_assignments: number;
        };
        /**
         * GetDraftResponse
         * @description Model that represents a response for getting a draft assignment.
         */
        GetDraftResponse: {
            /** Assignment Id */
            assignment_id: number;
            /** Name */
            name: string;
            /** Is Group */
            is_group: boolean;
        };
        /**
         * GetDropdownResponse_Assignment
         * @description Model that represents an assignment in the dropdown response.
         */
        GetDropdownResponse_Assignment: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            state: components["schemas"]["AssignmentState"];
        };
        /**
         * GetDropdownResponse_Course
         * @description Model that represents a course in the dropdown response.
         */
        GetDropdownResponse_Course: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Is Staff */
            is_staff: boolean;
        };
        /**
         * GetGroupProjectsResponse
         * @description Model that represents a response for getting group projects of an assignment.
         */
        GetGroupProjectsResponse: {
            /** Projects */
            projects: components["schemas"]["GetGroupProjectsResponse_Project"][];
        };
        /**
         * GetGroupProjectsResponse_Project
         * @description Model that represents a group in the response for getting group projects of an assignment.
         */
        GetGroupProjectsResponse_Project: {
            /** Project Id */
            project_id: number;
            /** Group Id */
            group_id: number;
            /** Group Name */
            group_name: string;
            /** Group Members */
            group_members: string[];
            /** Group Member Emails */
            group_member_emails: string[];
            /** Db Url */
            db_url: string;
        };
        /**
         * GetGroupsResponse
         * @description Model that represents a response for getting groups of an assignment.
         */
        GetGroupsResponse: {
            /** Groups */
            groups: components["schemas"]["GetGroupsResponse_Group"][];
            /** Unassigned Students */
            unassigned_students: components["schemas"]["GetGroupsResponse_User"][];
        };
        /**
         * GetGroupsResponse_Group
         * @description Model that represents a group in the response for getting groups of an assignment.
         */
        GetGroupsResponse_Group: {
            /** Group Id */
            group_id: number;
            /** Group Name */
            group_name: string;
            /** Members */
            members: components["schemas"]["GetGroupsResponse_User"][];
        };
        /**
         * GetGroupsResponse_User
         * @description Model that represents a member of a group in the response for getting groups of an assignment.
         */
        GetGroupsResponse_User: {
            /** User Id */
            user_id: number;
            /** User Name */
            user_name: string;
        };
        /**
         * GetProfileSummaryResponse
         * @description Model that represents a response for the profile endpoint.
         */
        GetProfileSummaryResponse: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email */
            email: string;
            /** Initials */
            initials: string;
        };
        /**
         * GetRoleForCourseResponse
         * @description Model that represents the role of a user in a course.
         */
        GetRoleForCourseResponse: {
            role?: components["schemas"]["CourseMembershipRole"] | null;
            /**
             * Is Staff
             * @default false
             */
            is_staff: boolean;
            /**
             * Can Modify Assignments
             * @default false
             */
            can_modify_assignments: boolean;
        };
        /**
         * GetStaffViewResponse
         * @description Model that presents the information for a staff view of an assignment.
         */
        GetStaffViewResponse: {
            /** Assignment Id */
            assignment_id: number;
            /** Name */
            name: string;
            /** Is Group */
            is_group: boolean;
            state: components["schemas"]["AssignmentState"];
            /** Configuration Sql */
            configuration_sql?: string | null;
        };
        /**
         * GetStudentProjectsResponse
         * @description Model that represents a response for getting student projects of an assignment.
         */
        GetStudentProjectsResponse: {
            /** Projects */
            projects: components["schemas"]["GetStudentProjectsResponse_Project"][];
        };
        /**
         * GetStudentProjectsResponse_Project
         * @description Model that represents a project in the response for getting student projects.
         */
        GetStudentProjectsResponse_Project: {
            /** Project Id */
            project_id: number;
            /** User Id */
            user_id: number;
            /** User Name */
            user_name: string;
            /** User Email */
            user_email: string;
            /** Db Url */
            db_url: string;
        };
        /**
         * GetStudentsForCourseResponse
         * @description Model that represents a response for getting students in a course.
         */
        GetStudentsForCourseResponse: {
            /** Students */
            students: components["schemas"]["GetStudentsForCourseResponse_Student"][];
        };
        /**
         * GetStudentsForCourseResponse_Student
         * @description Model that represents a student in the course students response.
         */
        GetStudentsForCourseResponse_Student: {
            /** User Id */
            user_id: number;
            /** User Name */
            user_name: string;
        };
        /**
         * GetViewResponse
         * @description Model that represents a response for viewing an assignment.
         */
        GetViewResponse: {
            role: components["schemas"]["CourseMembershipRole"];
            assignment_state: components["schemas"]["AssignmentState"];
            /**
             * Should Redirect
             * @default false
             */
            should_redirect: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Task
         * @description Represents a Celery asychronous task.
         */
        Task: {
            /** Task Id */
            task_id: string;
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "PENDING" | "RECEIVED" | "STARTED" | "SUCCESS" | "FAILURE" | "RETRY" | "REVOKED" | "IGNORED";
        /**
         * TaskStatusResponse
         * @description Represents the status of a Celery task.
         */
        TaskStatusResponse: {
            /** Task Id */
            task_id: string;
            status: components["schemas"]["TaskStatus"];
            /** Result */
            result?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * TestConfigurationSQLRequest
         * @description Model that represents a request to test the configuration SQL for an assignment.
         */
        TestConfigurationSQLRequest: {
            /** Sql */
            sql: string;
        };
        /**
         * TestConfigurationSQLResponse
         * @description Model that represents a response to testing the configuration SQL for an assignment.
         */
        TestConfigurationSQLResponse: {
            /** Success */
            success: boolean;
            /** Error Message */
            error_message?: string | null;
            /** Db Url */
            db_url?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * GetDropdownResponse
         * @description Model that represents a response for the dropdown endpoint.
         */
        server__models__assignment__GetDropdownResponse: {
            selected_assignment?: components["schemas"]["GetDropdownResponse_Assignment"] | null;
            /** Assignments */
            assignments: components["schemas"]["GetDropdownResponse_Assignment"][];
        };
        /**
         * GetDropdownResponse
         * @description Model that represents a dropdown response.
         */
        server__models__course__GetDropdownResponse: {
            /** Terms */
            terms: string[];
            selected_course?: components["schemas"]["GetDropdownResponse_Course"] | null;
            /** Courses */
            courses: {
                [key: string]: components["schemas"]["GetDropdownResponse_Course"][];
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    get_task_status_api_task__task_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    auth_unc_api_project__project_id__auth_unc_get: {
        parameters: {
            query?: {
                continue_to?: string;
            };
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_unc_callback_api_project__project_id__auth_unc_callback_get: {
        parameters: {
            query: {
                token: string;
                continue_to?: string;
            };
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_course_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetDashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dropdown_api_course_dropdown_get: {
        parameters: {
            query?: {
                search?: string;
                selected_course_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["server__models__course__GetDropdownResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assignments_api_course__course_id__assignments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAssignmentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_role_api_course__course_id__role_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRoleForCourseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_students_api_course__course_id__students_get: {
        parameters: {
            query?: {
                search?: string;
            };
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetStudentsForCourseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_profile_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetProfileSummaryResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dropdown_api_assignment_dropdown_get: {
        parameters: {
            query: {
                course_id: number;
                search?: string;
                selected_assignment_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["server__models__assignment__GetDropdownResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_view_api_assignment__assignment_id__view_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetViewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_api_assignment__assignment_id__draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_configuration_sql_api_assignment__assignment_id__configuration_sql_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetConfigurationSQLResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_staff_view_api_assignment__assignment_id__staff_view_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetStaffViewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_student_projects_api_assignment__assignment_id__student_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetStudentProjectsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_group_projects_api_assignment__assignment_id__group_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetGroupProjectsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_draft_api_assignment_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_api_assignment__assignment_id__rename_put: {
        parameters: {
            query: {
                name: string;
            };
            header?: never;
            path: {
                assignment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_configuration_sql_api_assignment__assignment_id__configuration_sql_test_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestConfigurationSQLRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestConfigurationSQLResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_configuration_sql_api_assignment__assignment_id__configuration_sql_save_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_configuration_sql_api_assignment__assignment_id__configuration_sql_remove_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_configuration_sql_api_assignment__assignment_id__configuration_sql_reset_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_groups_api_assignment__assignment_id__groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetGroupsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_group_api_assignment__assignment_id__group__group_id__rename_put: {
        parameters: {
            query: {
                name: string;
            };
            header?: never;
            path: {
                assignment_id: number;
                group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_group_api_assignment__assignment_id__group_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateGroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_group_api_assignment__assignment_id__group__group_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: number;
                group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_group_member_api_assignment__assignment_id__group__group_id__member_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddGroupMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_group_member_api_assignment__assignment_id__group__group_id__member__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: number;
                group_id: number;
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_assignment_api_assignment__assignment_id__publish_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_assignment_api_assignment__assignment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
