/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logs out the user by clearing the auth token cookie.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/{project_id}/auth/unc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Unc
         * @description This endpoint initiates authentication to the UNC SSO proxy for a project. The proxy will
         *     respond with an authorization token and call the `/unc/callback` endpoint for Tinkerbase
         *     to continue the UNC SSO authentication flow.
         */
        get: operations["auth_unc_api_project__project_id__auth_unc_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/{project_id}/auth/unc/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Unc Callback
         * @description This endpoint is called by the UNC SSO proxy after the user has authenticated with UNC SSO.
         *     Tinkerbase will verify the token and issue a JWT token for the user to be authenticated.
         */
        get: operations["auth_unc_callback_api_project__project_id__auth_unc_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_course_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/dropdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dropdown */
        get: operations["get_dropdown_api_course_dropdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{course_id}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Assignments
         * @description Get assignments for a specific course.
         */
        get: operations["get_assignments_api_course__course_id__assignments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/course/{course_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Course Role
         * @description Get the role of the user in the specified course.
         */
        get: operations["get_course_role_api_course__course_id__role_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_api_profile_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/dropdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dropdown */
        get: operations["get_dropdown_api_assignment_dropdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/{assignment_id}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get View */
        get: operations["get_view_api_assignment__assignment_id__view_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/{assignment_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_api_assignment__assignment_id__draft_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Draft */
        post: operations["create_draft_api_assignment_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignment/{assignment_id}/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Rename
         * @description Rename an existing assignment.
         */
        put: operations["rename_api_assignment__assignment_id__rename_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssignmentState
         * @description Enum identifying the various states an assignment can be in.
         * @enum {string}
         */
        AssignmentState: "draft" | "unpublished" | "published";
        /**
         * CourseMembershipRole
         * @description Enum identifying the level of permissions for a course member.
         * @enum {string}
         */
        CourseMembershipRole: "owner" | "admin" | "staff" | "student";
        /**
         * CreateDraftRequest
         * @description Model that represents a request to create a draft.
         */
        CreateDraftRequest: {
            /** Name */
            name: string;
            /** Course Id */
            course_id: number;
            /** Is Group */
            is_group: boolean;
        };
        /**
         * CreateDraftResponse
         * @description Model that represents a response to creating a draft.
         */
        CreateDraftResponse: {
            /** Assignment Id */
            assignment_id: number;
        };
        /**
         * GetAssignmentsResponse
         * @description Model that represents a response for the assignments endpoint.
         */
        GetAssignmentsResponse: {
            /** Is Staff */
            is_staff: boolean;
            /** Assignments */
            assignments: components["schemas"]["GetAssignmentsResponse_Assignment"][];
        };
        /**
         * GetAssignmentsResponse_Assignment
         * @description Model that represents an assignment in the assignments response.
         */
        GetAssignmentsResponse_Assignment: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Is Group */
            is_group: boolean;
            state: components["schemas"]["AssignmentState"];
        };
        /**
         * GetDashboardResponse
         * @description Model that represents a response for the dashboard endpoint.
         */
        GetDashboardResponse: {
            /** Most Recent Staff Course Term */
            most_recent_staff_course_term: string | null;
            /** Most Recent Student Course Term */
            most_recent_student_course_term: string | null;
            /** Other Staff Course Terms */
            other_staff_course_terms: string[];
            /** Other Student Course Terms */
            other_student_course_terms: string[];
            /** Staff Courses */
            staff_courses: {
                [key: string]: components["schemas"]["GetDashboardResponse_Course"][];
            };
            /** Student Courses */
            student_courses: {
                [key: string]: components["schemas"]["GetDashboardResponse_Course"][];
            };
        };
        /**
         * GetDashboardResponse_Course
         * @description Model that represents a course in the dashboard response.
         */
        GetDashboardResponse_Course: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Num Students */
            num_students?: number | null;
            /** Num Assignments */
            num_assignments: number;
        };
        /**
         * GetDraftResponse
         * @description Model that represents a response for getting a draft assignment.
         */
        GetDraftResponse: {
            /** Assignment Id */
            assignment_id: number;
            /** Name */
            name: string;
            /** Is Group */
            is_group: boolean;
        };
        /**
         * GetDropdownResponse_Assignment
         * @description Model that represents an assignment in the dropdown response.
         */
        GetDropdownResponse_Assignment: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            state: components["schemas"]["AssignmentState"];
        };
        /**
         * GetDropdownResponse_Course
         * @description Model that represents a course in the dropdown response.
         */
        GetDropdownResponse_Course: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Is Staff */
            is_staff: boolean;
        };
        /**
         * GetProfileSummaryResponse
         * @description Model that represents a response for the profile endpoint.
         */
        GetProfileSummaryResponse: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email */
            email: string;
            /** Initials */
            initials: string;
        };
        /**
         * GetRoleForCourseResponse
         * @description Model that represents the role of a user in a course.
         */
        GetRoleForCourseResponse: {
            role?: components["schemas"]["CourseMembershipRole"] | null;
            /**
             * Is Staff
             * @default false
             */
            is_staff: boolean;
            /**
             * Can Modify Assignments
             * @default false
             */
            can_modify_assignments: boolean;
        };
        /**
         * GetViewResponse
         * @description Model that represents a response for viewing an assignment.
         */
        GetViewResponse: {
            role: components["schemas"]["CourseMembershipRole"];
            assignment_state: components["schemas"]["AssignmentState"];
            /**
             * Should Redirect
             * @default false
             */
            should_redirect: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * GetDropdownResponse
         * @description Model that represents a response for the dropdown endpoint.
         */
        server__models__assignment__GetDropdownResponse: {
            selected_assignment?: components["schemas"]["GetDropdownResponse_Assignment"] | null;
            /** Assignments */
            assignments: components["schemas"]["GetDropdownResponse_Assignment"][];
        };
        /**
         * GetDropdownResponse
         * @description Model that represents a dropdown response.
         */
        server__models__course__GetDropdownResponse: {
            /** Terms */
            terms: string[];
            selected_course?: components["schemas"]["GetDropdownResponse_Course"] | null;
            /** Courses */
            courses: {
                [key: string]: components["schemas"]["GetDropdownResponse_Course"][];
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    auth_unc_api_project__project_id__auth_unc_get: {
        parameters: {
            query?: {
                continue_to?: string;
            };
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_unc_callback_api_project__project_id__auth_unc_callback_get: {
        parameters: {
            query: {
                token: string;
                continue_to?: string;
            };
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_course_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetDashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dropdown_api_course_dropdown_get: {
        parameters: {
            query?: {
                search?: string;
                selected_course_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["server__models__course__GetDropdownResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assignments_api_course__course_id__assignments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAssignmentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_role_api_course__course_id__role_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRoleForCourseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_profile_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetProfileSummaryResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dropdown_api_assignment_dropdown_get: {
        parameters: {
            query: {
                course_id: number;
                search?: string;
                selected_assignment_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["server__models__assignment__GetDropdownResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_view_api_assignment__assignment_id__view_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetViewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_api_assignment__assignment_id__draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_draft_api_assignment_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_api_assignment__assignment_id__rename_put: {
        parameters: {
            query: {
                name: string;
            };
            header?: never;
            path: {
                assignment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
